### ISSUE TITLE
Slip 13 infinitely looping

### ISSUE THREAD

**Issue by GetAwayCoxn** [ThornyFFXI/Porter#1]
So I think I know what is going on here but lets start with a fairly uninformative screenshot:

![Igotudis_2022 07 19_101724](https://user-images.githubusercontent.com/66495755/179776969-f377581b-5919-48cb-8eb2-2fda26616694.png)

I was trying to just do a normal storage routine to clean up my inventory and going to do some other content and I got stuck in a slow but infinite loop here and had to force close the client after grabbing a snip it. Looking at what pieces go into slip13 I know that at the time had 2 un-augmented +2 relic pieces in my inventory probably causing this. I moved one piece out of the reach of porter and tried again and got the same issue but now with just the one remaining un-aug'd relic +2 in my inv. I didn't look into how your checking items if its by name or ID or whatever since you will obviously know right away but might need to add an augment check (or kick out or whatever) for slip 13 or any other slip that requires the item to be augmented to be stored if any other exist.

Running on all current versions etc.

**Comment by ThornyFFXI** [comment]
Should be fixed in 1.03, I don't have any relic+2 to confirm with at the moment.  If it persists, feel free to message me or open a new ticket and I'll farm a piece to verify further.
