### ISSUE TITLE
Nil error crash on pre pack

### ISSUE THREAD

**Issue by GetAwayCoxn** [ThornyFFXI/Porter#2]
Since our conversation the other week about porter not handling augments I didnt update with your fix until today, I didn't have anymore older gear like that and so I just left it on old version being lazy. Got another +2 un aug'd piece today so i updated to your latest so I could test out your fix and it crashes on pre pack, nil reference error, SS below. I did one quick reload and crashed it again just so I could quickly dbl check the version number for the SS.

![Igotudis_2022 07 31_124848](https://user-images.githubusercontent.com/66495755/182037055-0ab77119-974b-4a6d-a4ae-0be10d1a271c.png)

**Comment by ThornyFFXI** [comment]
Took one more crack at it.  If this doesn't work, I'll farm a piece to verify conclusively.

**Comment by GetAwayCoxn** [comment]
Had a couple random pieces on a mule, seems to be good now, thank you!
