### ISSUE TITLE
Softlocks the game if you request a Rare item that's already in your inventory

### ISSUE THREAD

**Issue by ChristopherJTrent** [ThornyFFXI/Porter#6]
I mistakenly obtained 2 Chasseur's Tricornes +2, one in my storage slip, one in my inventory. 
I used /lac unpack to get all of my gear set up as I usually do, and when I did, Porter got in an infinite loop of trying to grab the hat, failing because I already have one in my inventory, and trying again. 

Because porter blocks all input while it's trying to gather gear, the only way to escape this loop was to kill the game from the task manager.

**Comment by ThornyFFXI** [comment]
Fixed in 1.11, thank you for reporting.
